"""Pydantic schemas for geographic data — Section 2.3 of PRD/TRD."""
from typing import Optional, Literal
from pydantic import BaseModel, Field


# =============================================================================
# geo_lookup — precomputed nearest-verified-facility per PIN code × capability
# =============================================================================

class GeoLookup(BaseModel):
    """Precomputed nearest verified facility for a PIN code and capability."""
    pin_code: str
    capability: str
    nearest_facility_id: str
    distance_km: float
    travel_time_minutes: Optional[int] = Field(None, description="Populated if isochrones built")
    nearest_trust_score: int
    desert_severity: Literal["green", "yellow", "red"] = Field(
        ...,
        description="green: <50km, yellow: 50-100km, red: >100km"
    )


# =============================================================================
# facility_embeddings — Mosaic AI Vector Search index source
# =============================================================================

class FacilityEmbedding(BaseModel):
    """Facility embedding record for vector search."""
    facility_id: str = Field(..., description="Primary key")
    profile_text: str = Field(..., description="Concatenated structured profile for embedding")
    embedding: Optional[list[float]] = Field(
        None,
        description="1024-dim, auto-generated by bge-large-en via Vector Search Delta sync"
    )
